# Generated by Django 3.0.8 on 2020-07-08 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, max_length=100, null=True)),
                ('tasktitle', models.CharField(max_length=250)),
                ('taskdescription', models.TextField()),
                ('taskstate', models.CharField(choices=[('To do', 'Todo'), ('In progress', 'Inprogress'), ('Done', 'Done')], default='To do', max_length=50)),
                ('taskduedate', models.DateField(default=datetime.datetime(2020, 7, 8, 22, 58, 4, 374514))),
            ],
        ),
    ]
