# Generated by Django 3.0.8 on 2020-07-08 23:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BEapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskduedate',
            field=models.DateField(default=datetime.datetime(2020, 7, 8, 23, 0, 1, 546174, tzinfo=utc)),
        ),
    ]
