# Generated by Django 3.0.8 on 2020-07-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEapi', '0002_auto_20200708_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskduedate',
            field=models.DateField(),
        ),
    ]
