# Generated by Django 3.0.8 on 2020-07-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEapi', '0004_auto_20200708_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskduedate',
            field=models.DateField(),
        ),
    ]
