# Generated by Django 3.0.8 on 2020-07-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEapi', '0005_auto_20200708_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskdescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasktitle',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
