# Generated by Django 3.0.8 on 2020-07-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEapi', '0006_auto_20200709_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSerializer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='taskduedate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasktitle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
