# Generated by Django 3.0.8 on 2020-07-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEapi', '0008_auto_20200709_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskduedate',
            field=models.DateField(),
        ),
    ]
